target("lcgs-test")
    set_kind("binary")
    add_packages("luisa-compute")
    on_config(function (target)
        target:add("runargs", path.join(target:pkg("luisa-compute"):installdir(), "bin"))
        end)
    add_files("*.cpp")
    add_deps("lcgs")
    add_includedirs("_framework")
    add_files("_framework/test_util.cpp")